# Generated by Django 5.0.3 on 2024-03-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerForge', '0002_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
