# Generated by Django 5.0.3 on 2024-03-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CareerForge', '0002_initial'),
        ('TalentHub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalentHub.joblisting'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerForge.jobseekerprofile'),
        ),
    ]
