# Generated by Django 5.0.3 on 2024-03-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerForge', '0005_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
