# Generated by Django 5.0.3 on 2024-03-25 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHub', '0004_joblisting_status'),
        ('user_management', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalentHub.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
