# Generated by Django 5.0.3 on 2024-03-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_reportedissue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportedIssue',
        ),
    ]
